# Even Fibonacci numbers
# Problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

from typing import Generator


def fibonacci(a: int = 1, b: int = 1) -> Generator[int, None, None]:
    '''iterates through the fibonacci numbers'''
    yield a + b
    yield from fibonacci(b, a + b)


def solve() -> int:
    '''Problem 2 - Even Fibonacci numbers'''
    limit = 4 * 10 ** 6
    answer = 0
    for fib in fibonacci():
        if fib > limit:
            break
        if fib % 2 == 0:
            answer += fib
    return answer


if __name__ == "__main__":
    print(solve())
